// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LateralTools: typeof import('./src/components/lateralTools/index.vue')['default']
    PublicTools: typeof import('./src/components/publicTools/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VtoComponents: typeof import('./src/components/vtoComponents.vue')['default']
  }
}

export {}
